### PR TITLE
Add Bash syntax highlighting to `README.md`

### PR DESCRIPTION
**Pull request by Benjamin-Loison**

### CODE REVIEW

**Comment by detly** [comment]
It's not actually Bash syntax though, it's showing a command and the output of the program itself.

**Comment by Benjamin-Loison** [comment]
I agree that adding Bash syntax highlighting is debatable in this case.
Just to know your opinion, if [the `>` characters were not red syntax highlighted](https://github.com/Benjamin-Loison/arkfind/blob/95529a55b6c763ec8fcd1f923874932509647362/README.md#examples), would it make sense to add the Bash syntax highlighting anyway?

**Comment by detly** [comment]
> if [the `>` characters were not red syntax highlighted](https://github.com/Benjamin-Loison/arkfind/blob/95529a55b6c763ec8fcd1f923874932509647362/README.md#examples), would it make sense to add the Bash syntax highlighting anyway?

I don't think so, honestly — it's simply not a bash script. The only shell syntax at all is the command invocation, the preceding `$ ` is just convention, and wouldn't be found in a bash script; the following text is program output, which is not related to bash's control flow.

**Comment by Benjamin-Loison** [comment]
I understand, thank you for your feedback.

**Pull request closed without merging**
